[package]
name = "kvs"
version = "0.1.0"
authors = ["longfangsong <longfangsong@icloud.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = "2.33.0"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.4"


