[package]
name = "mini-kv"
version = "0.1.0"
authors = ["longfangsong <longfangsong@icloud.com>"]
edition = "2018"

[dependencies]
rpc = { path = "rpc" }
grpcio = "0.5.1"
futures = {version = "0.3.4", features = ["compat"]}
futures01 = { package = "futures", version = "0.1"}
futures-locks = "0.5.0"
log = "0.4.8"
env_logger = "0.7.1"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dev-dependencies]
pprof = "0.3.16"
tempfile = "3.1.0"
